### ISSUE TITLE
Package not available 

### ISSUE THREAD

**Issue by prasunsrivastava** [AugustoPinheiro/RN-react-native-document-scanner#10]
Hi,

Thanks for posting this. However, it looks like the original package for performing the scan is in a parent directory. 
```
"react-native-document-scanner": "../",
```
Would you mind pushing the parent directory too; otherwise this does not work.

Thank You.

**Comment by AugustoPinheiro** [comment]
Pls try again

**Comment by AugustoPinheiro** [comment]
https://github.com/AugustoPinheiro/RN-react-native-document-scanner/commit/fa6a552a2cf8509dc05e364229ce83231a0d7687
