### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not determine the dependencies of task ':app:preDebugBuild'. > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.    > Could not resolve project :react-native-document-scanner.      Required by:          project :app       > Unable to find a matching configuration of project :react-native-document-scanner: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by TalalBhatti** [AugustoPinheiro/RN-react-native-document-scanner#11]
I'm new and tried to do everything but it doesn't resolve

**Comment by psvnlsaikumar** [comment]
@TalalBhatti any luck?

**Comment by TalalBhatti** [comment]
@psvnlsaikumar No bro. I'm switching to backend processing by sending frames from the Python backend. As soon as my backend process gets successful I would redirect. to enhance UI I'm using some pre-animations rather than real-time detection.

**Comment by AugustoPinheiro** [comment]
I have updated the repository, try again https://github.com/AugustoPinheiro/RN-react-native-document-scanner/commit/fa6a552a2cf8509dc05e364229ce83231a0d7687

**Comment by TalalBhatti** [comment]
@AugustoPinheiro it gives error on build for the react-native-document-scanner 

Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-document-scanner.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-document-scanner: None of the consumable configurations have attributes.
