### ISSUE TITLE
Steps to run the example?

### ISSUE THREAD

**Issue by AyushExel** [AugustoPinheiro/RN-react-native-document-scanner#12]
I tried running the example but I'm not able to. Here are the steps I used:
* git clone
* cd example
* npm i
* react-native run-android
This throws an error - `Unable to find a matching configuration of project :react-native-document-scanner`

I tried random things:
* I tried yarn install but that failed with some error.

Can you please provide the exact steps to run the example? I wasn't able to import this tool in my existing project maybe due to some linking issue I was getting `RNPdfScanner not fond in UIManager` so I'll just build the example and add my existing work into this. Any help to successfully execute the example will be much appreciated. Thanks!
@AugustoPinheiro

**Comment by AugustoPinheiro** [comment]
### Mostly automatic installation

`$ react-native link react-native-document-scanner`

### Manual installation

#### iOS

1. In XCode, in the project navigator, right click `Libraries` ➜ `Add Files to [your project's name]`
2. Go to `node_modules` ➜ `react-native-document-scanner` and add `RNDocumentScanner.xcodeproj`
3. In XCode, in the project navigator, select your project. Add `libRNDocumentScanner.a` to your project's `Build Phases` ➜ `Link Binary With Libraries`
4. Add OpenCV in your `Podfile` :
   ```
   ...
     # Pods for [your project]
     pod 'libopencv-contrib', '~> 3.4.1'
   end
   ```
5. Run `pod install` in your ios folder
6. Run your project (`Cmd+R`)<

#### Android

1. Open up `android/app/src/main/java/[...]/MainActivity.java`

- Add `import com.ubidreams.RNDocumentScanner.RNDocumentScannerPackage;` to the imports at the top of the file
- Add `new RNDocumentScannerPackage()` to the list returned by the `getPackages()` method

2. Append the following lines to `android/settings.gradle`:
   ```
   include ':react-native-document-scanner'
   project(':react-native-document-scanner').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-document-scanner/android')
   ```
3. Insert the following lines inside the dependencies block in `android/app/build.gradle`:
   ```
     compile project(':react-native-document-scanner')
   ```

## Dependencies

- [React Native Camera](https://react-native-community.github.io/react-native-camera/docs/installation)
- [React Native SVG](https://github.com/react-native-community/react-native-svg#installation)

## Usage

```javascript
import RNDocumentScanner from 'react-native-document-scanner'

render () {
  return (
    <View style={styles.container}>
      <RNDocumentScanner />
    </View>
  )
}

**Comment by AyushExel** [comment]
@AugustoPinheiro thanks for the reply. I was asking about the example app in the `example` folder of the repo. Some of these are steps that shouldn't be needed for that right? Isn't linking already done there?

**Comment by AyushExel** [comment]
@AugustoPinheiro btw, on running `react-native link react-native-document-scanner` after running `npm install` inside the `example/` folder, I'm getting this error:
```
(node:63914) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by abazudosen** [comment]
nothing works here

**Comment by AdityaTarale** [comment]
Hi @AugustoPinheiro could you please drop step to run the example , i see android ios scripts also missing in the package.json , It will very much thankful to clear the issue. :)

**Comment by AugustoPinheiro** [comment]
fixed.
