### ISSUE TITLE
Could not find org.piwik.sdk:piwik-sdk:0.0.4

### ISSUE THREAD

**Issue by mopilo** [AugustoPinheiro/RN-react-native-document-scanner#13]
Could not determine the dependencies of task ':react-native-document-scanner:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-document-scanner:debugCompileClasspath'.
   > Could not find org.piwik.sdk:piwik-sdk:0.0.4.
     Required by:
         project :react-native-document-scanner
   > Could not find us.feras.mdv:markdownview:1.1.0.
     Required by:
         project :react-native-document-scanner

**Comment by harbolaez** [comment]
What's the solution here?

**Comment by vijaysahani4115** [comment]
@harbolaez  did you found any sol ?
