### ISSUE TITLE
Cant able to Run project 

### ISSUE THREAD

**Issue by gowtham171** [AugustoPinheiro/RN-react-native-document-scanner#2]
> Task :app:compileDebugJavaWithJavac FAILED

C:\Users\Gowtham.C\Downloads\New folder (4)\RN-react-native-document-scanner-main\android\app\src\main\java\com\example\MainApplication.java:7: error: package com.ubidreams.RNDocumentScanner does not exist
import com.ubidreams.RNDocumentScanner.RNDocumentScannerPackage;
                                      ^
C:\Users\Gowtham.C\Downloads\New folder (4)\RN-react-native-document-scanner-main\android\app\src\main\java\com\example\MainApplication.java:30: 
error: cannot find symbol
            new RNDocumentScannerPackage(),
                ^
  symbol: class RNDocumentScannerPackage
2 errors

FAILURE: Build failed with an exception.

**Comment by AugustoPinheiro** [comment]
Please make sure your installation order is the same as the following.

### Mostly automatic installation

`$ react-native link react-native-document-scanner`

**Comment by AugustoPinheiro** [comment]
What specifications of the dependencies on your computer?

**Comment by tech247gb** [comment]
Same error after following the steps
