### ISSUE TITLE
"RNPdfScanner" was not found in the UIManager

### ISSUE THREAD

**Issue by quanghungit** [AugustoPinheiro/RN-react-native-document-scanner#3]
Help me !!! Do you have this problem?

**Comment by quanghungit** [comment]
I run the app on android.

**Comment by AugustoPinheiro** [comment]
Usualy the "invariant violation" issue can indicate that you didn't run "react-native link" correctly. Can you give it a try ?

**Comment by quanghungit** [comment]
I ran "react-native link" but it still doesn't work :(

**Comment by AugustoPinheiro** [comment]
What the config are you trying to run this?

"react": - ?
"react-native": - ?
"react-native-document-scanner": " - ?

**Comment by quanghungit** [comment]
"react": "17.0.1",
 "react-native": "^0.64.2",
"react-native-document-scanner": "^1.4.2",

**Comment by AugustoPinheiro** [comment]
can you please upload the example for android in index.android.js as you upload the example for ios in index.ios.js

**Comment by AugustoPinheiro** [comment]
Ok.

Try these steps 🚶

1- yarn add react-native-document-scanner
2- cd ios
3- pod install
4 - pod update 
3- close and re-run the app on the phone 📱

**Comment by AlwinPonnan** [comment]
i'm having same error , can you help

**Comment by AugustoPinheiro** [comment]
hey @AlwinPonnan !!

What the config are you trying to run this?

"react": - ?
"react-native": - ?
"react-native-document-scanner": " - ?
