### ISSUE TITLE
Package not included

### ISSUE THREAD

**Issue by ByronDev121** [AugustoPinheiro/RN-react-native-document-scanner#5]
Hi,

It looks like the plugin is in a parent directory "../" and so the app cannot be installed.

I'm very interested in using this package would you mind please sharing the content of the RN-ract-native-document-scanner from the parent dir?

**Comment by AugustoPinheiro** [comment]
Hey, 

I will add in the next week, pls watch the repo. :)

**Comment by dancomanio** [comment]
Any update?
