### ISSUE TITLE
npm install react-native-document-scanner is not working

### ISSUE THREAD

**Issue by emanu7478** [AugustoPinheiro/RN-react-native-document-scanner#6]
When I'm trying to execute npm install react-native-document-scanner it showing error as like below
<img width="700" alt="Screenshot 2021-09-17 at 5 01 45 PM" src="https://user-images.githubusercontent.com/31894565/133775825-38047cbe-1a56-4625-88bb-d7416b6de206.png">

I had tried by removing node modules but then also installation in not possible. Could you help me to solve this issue ?

**Comment by AugustoPinheiro** [comment]
try to use` react-native install react-native-document-scanner`
